// Mahdiar Shoraka All Rights Reserved

#pragma once

#include "NativeGameplayTags.h"

namespace SoulsGameplayTags
{
	/** Input Tags **/
	SOULSCLONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	SOULSCLONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	SOULSCLONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipAxe);
	SOULSCLONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnequipAxe);
	SOULSCLONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack_Axe);
	SOULSCLONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HeavyAttack_Axe);
	
	/** Player tags **/
	SOULSCLONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Axe);
	SOULSCLONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Axe);
	SOULSCLONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Light_Axe);
	SOULSCLONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Heavy_Axe);
	SOULSCLONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_HitPause);
	
	SOULSCLONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Axe);

	SOULSCLONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Axe);
	SOULSCLONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip_Axe);
	SOULSCLONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_HitPause);

	SOULSCLONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_JumpToFinisher);

	SOULSCLONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Light);
	SOULSCLONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Heavy);
	
	/** Enemy tags **/
	SOULSCLONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Melee);
	SOULSCLONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Ranged);
	
	SOULSCLONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Weapon);

	/** Shared tags **/
	SOULSCLONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_HitReact);
	SOULSCLONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_Death);
	
	SOULSCLONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_MeleeHit);
	SOULSCLONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact);
	
	SOULSCLONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_SetByCaller_BaseDamage);

	SOULSCLONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Death);
	
}
